species: Chinook

run_dir: .test/data  # set it on the command line to the directory in which raw, samples.csv, and units.csv reside

# the following are names of files that are assumed to be
# within the run_dir.  NOTE! These names might be hardwired
# in extract_microhaplotypes.R.  Don't change these...
samples: samples.csv
units: units.csv


# by default, we don't use trimmomatic.  But you can give
# --config use_trimmomatic=true to use it with the parameters
# as specificied below.
use_trimmomatic: false

# here are some parameters and things for trimmomatic trimming,
# for the way that Jeff Rodzen does it.
trimmo_adapter_opt: ILLUMINACLIP:config/Mykiss/adapters/GTseq-PE.fa:2:40:15
trimmo_opts: "LEADING:2 TRAILING:2 SLIDINGWINDOW:4:2 MINLEN:40"

# set genomes up to be downloaded from url.  They will
# be placed in resources/{species_dir}/genomes/name_of_genome/name_of_genome.fna
# where name_of_genome is like Otsh_v1.0
genomes:
  Otsh_v1.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/872/995/GCF_002872995.1_Otsh_v1.0/GCF_002872995.1_Otsh_v1.0_genomic.fna.gz

#Testing adding env modules here
env:
  ohpc: "ohpc"
  tidyv: "tidyverse/2.0.0"
#  R: "R/4.3.0"

# here we give details about our marker sets.  Note that a marker
# set can be both genome-focused and target_fasta-focused, as
# I have done with ROSA here, just for an example.

# Note also that we have allowed for two different target_fastas
# for ROSA which will give us two different possible ROSA sets, possibly.
# It seemed like that would be good in order to test different
# target_fastas side-by-side, etc.

# Also, each target_fasta is assumed to belong to only one marker_set,
# but a particular full genome can belong to multiple marker sets.

# And we can map a marker set to more than one full genome...as the
# LFAR example with a genome called "nookie2" shows.

# But, also note that we can have multiple variant sets for each genome
# within a genome-focused marker set.

# The "variants" field is reserved only for the canonical SNP-sets that we would
# use to call specific variants.  Not for finding new variants, etc.
marker_sets:
  LFAR:
    genome:
      Otsh_v1.0:
        regions: config/Chinook/regions/LFAR-Otsh_v1.0.txt
        microhap_variants:
          all_variants: config/Chinook/canonical_variation/LFAR-all-snps-round-1.vcf
          after_5_runs: config/Chinook/canonical_variation/LFAR-8-amplicons-22-variants.vcf
  WRAP:
    genome:
      Otsh_v1.0:
        regions: config/Chinook/regions/WRAP-Otsh_v1.0.txt
        microhap_variants:
          all_variants: config/Chinook/canonical_variation/WRAP-all-snps-round-1.vcf
          after_5_runs: config/Chinook/canonical_variation/WRAP-24-amplicons-53-variants.vcf
  VGLL3SIX6:
    genome:
      Otsh_v1.0:
        regions: config/Chinook/regions/VGLL3SIX6-Otsh_v1.0.txt
        microhap_variants:
          single_snps: config/Chinook/canonical_variation/VGLL3SIX6-initial-sites.vcf
  ROSA:
    target_fasta:
      rosawr:
        fasta: config/Chinook/target_fastas/greb1_rosa_with_wrdiag_reference.fasta
        microhap_variants:
          all_variants: config/Chinook/canonical_variation/ROSA-rosawr-all-snps-round-1.vcf
  TRANSITION:
    target_fasta:
      transition_204:
        fasta: config/Chinook/target_fastas/chinook_204amps_transition.fasta
        microhap_variants:
          snplicons: config/Chinook/canonical_variation/chinook_204amps_ultima4_transition_multi_targets.vcf
  SNPS84:
    target_fasta:
      snps84:
        fasta: config/Chinook/target_fastas/chinook_84amps.fasta
        microhap_variants:
          single_snps: config/Chinook/canonical_variation/chinook_84amps_single_targets.vcf
  FullPanel:
    genome:
      Otsh_v1.0:
        regions: config/Chinook/regions/Chinook_FullPanel_VGLL3Six6LFARWRAP-Otsh_v1.0.txt
        microhap_variants:
          lfar_wrap_vgll3six6: config/Chinook/canonical_variation/Chinook_FullPanel_VGLL3Six6LFARWRAP-Otsh_v1.0.vcf
    target_fasta:
      target_fasta:
        fasta: config/Chinook/target_fastas/chinook_FullPanel_RosaTransition_March2024.fasta
        microhap_variants:
          rosa_microhap_snplicon: config/Chinook/canonical_variation/chinook_FullPanel_ROSATransition_March2024.vcf













