species: Chinook

run_dir: .test/data

# the following are names of files that are assumed to be
# within the run_dir
samples: samples.csv
units: units.csv

# set genomes up to be downloaded from url.  They will
# be placed in resources/genomes/name_of_genome/name_of_genome.fna
# where name_of_genome is like Otsh_v1.0
genomes:
  Otsh_v1.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/872/995/GCF_002872995.1_Otsh_v1.0/GCF_002872995.1_Otsh_v1.0_genomic.fna.gz
  nookie2:
    url: this_would_need_a_download_url_too



# NOTE: I should be able to replace the next 4 lines of code
# by simply cycling over config["marker_sets"] and making
# lists of the marker_sets that have a "genome" and those
# that have a "target_fasta".  But for now I leave it in here.
# The name element must be specified as a list here!
genome_focused_marker_sets:
  name: ["LFAR", "WRAP", "ROSA"]

# The name element must be specified as a list here!
target_fasta_focused_marker_sets:
  name: ["TRANSITION", "ROSA"]


# here we give details about our marker sets.  Note that a marker
# set can be both genome-focused and target_fasta-focused, as
# I have done with ROSA here, just for an example.

# Note also that we have allowed for two different target_fastas
# for ROSA which will give us two different possible ROSA sets, possibly.
# It seemed like that would be good in order to test different
# target_fastas side-by-side, etc.

# Also, each target_fasta is assumed to belong to only one marker_set,
# but a particular full genome can belong to multiple marker sets.

# And we can map a marker set to more than one full genome...as the
# LFAR example with a genome called "nookie2" shows.

# But, also note that we can have multiple variant sets for each genome
# within a genome-focused marker set.

# The "variants" field is reserved only for the canonical SNP-sets that we would
# use to call specific variants.  Not for finding new variants, etc.
marker_sets:
  LFAR:
    genome:
      Otsh_v1.0:
        regions: config/regions/LFAR-Otsh_v1.0.txt
        variants:
          snps_only: config/canonical_variants/LFAR-Otsh_v1-snps-only.vcf
          everything: config/canonical_variants/LFAR-Otsh_v1-everything.vcf
      nookie2:
        regions: config/regions/LFAR-nookie2.txt
  WRAP:
    genome:
      Otsh_v1.0:
        regions: config/regions/WRAP-Otsh_v1.0.txt
  ROSA:
    genome:
      Otsh_v1.0:
        regions: config/regions/ROSA-Otsh_v1.0.txt
    target_fasta:
      fasta:
        rosa_seqs_1: config/target_fastas/rosa-seqs-1-example.fasta
        rosa_seqs_2: config/target_fastas/rosa-seqs-2-example.fasta
      variants:
        snps_only: config/canonical_variants/Chinooks_RoSA_snps_only.vcf
        snplicons: config/canonical_variants/Chinooks_RoSA_all_variants.vcf
  TRANSITION:
    target_fasta:
      fasta:
        transition-panel: config/target_fastas/transition-panel.fna
      variants:
        snps_only: config/canonical_variants/Chinooks_transition_snps_only.vcf
        snplicons: config/canonical_variants/Chinooks_transitions_all_variants.vcf











