species: Chinook

run: gtseq01

# the following are names of files assumed to be
# within the run directory
samples: .test/data/samples.csv
units: .test/data/units.csv

# set genomes up to be downloaded from url.  They will
# be placed in resources/genomes/name_of_genome/name_of_genome.fna
# where name_of_genome is like Otsh_v1.0
genomes:
  Otsh_v1.0:
    url: put_here_the_download_url


genome_focused_marker_sets:
  name: ["LFAR", "WRAP", "ROSA"]

target_fasta_focused_marker_sets:
  name: TRANSITION

marker_sets:
  LFAR:
    genome:
      Otsh_v1.0:
        regions: config/regions/LFAR-Otsh_v1.0.txt
  WRAP:
    genome:
      Otsh_v1.0:
        regions: config/regions/WRAP-Otsh_v1.0.txt
  ROSA:
    genome:
      Otsh_v1.0:
        regions: config/regions/ROSA-Otsh_v1.0.txt
  TRANSITION:
    target_fasta: config/target_fastas/transition-panel-target-fasta.fna


