samples: samples.csv

species: Chinook

genome: genome/Otsh_v1.0_genomic.fna

samples:
  CHLFAR100: /home/eanderson/Documents/work/assist/anthony_clemento/LFAR-crunching/data/fastqs_LFAR_gtseq117/CHLFAR100.extendedFrags.fastq.gz
  CHLFAR101: /home/eanderson/Documents/work/assist/anthony_clemento/LFAR-crunching/data/fastqs_LFAR_gtseq117/CHLFAR101.extendedFrags.fastq.gz
  CHLFAR102: /home/eanderson/Documents/work/assist/anthony_clemento/LFAR-crunching/data/fastqs_LFAR_gtseq117/CHLFAR102.extendedFrags.fastq.gz
  CHLFAR103: /home/eanderson/Documents/work/assist/anthony_clemento/LFAR-crunching/data/fastqs_LFAR_gtseq117/CHLFAR103.extendedFrags.fastq.gz
regions:
  "NC_037130.1:1847885-1848185":
  "NC_037130.1:1062935-1063235":
  "NC_037130.1:786919-787219":
  "NC_037130.1:929833-930133":
  "NC_037130.1:536847-537147":
  "NC_037130.1:1845977-1846277":
  "NC_037130.1:828619-828919":
  "NC_037130.1:864908-865208":




